apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment 
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: backend
        image: shubhamshinde2025/threebackend:v10
        ports:
        - containerPort: 5000
---

apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: api
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 31100