apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vite
  name: vite
  namespace: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vite
  template:
    metadata:
      labels:
        app: vite
    spec:
      containers:
      - image:  shubhamshinde2206/node-app:5
        imagePullPolicy: Always
        name: vite
        ports:
        - containerPort: 5173
          protocol: TCP
