apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vite
  name: vite
  namespace: node-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vite
  strategy: {}
  template:
    metadata:
      labels:
        app: vite
    spec:
      containers:
      - image:  shubhamshinde2025/node-app:6
        imagePullPolicy: Always
        name: vite
        ports:
        - containerPort: 5173
          name: http
          protocol: TCP
