apiVersion: v1
kind: Service
metadata:
  labels:
    app: vite
  name: vite
  namespace: node-app
spec:
  type: LoadBalancer
  ports:
  - port: 5173
    protocol: TCP
    targetPort: 5173
  selector:
    app: vite 
