apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-mysql
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-mysql
  template:
    metadata:
      labels:
        app: zabbix-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "zabbix"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-mysql
  namespace: zabbix
spec:
  ports:
  - port: 3306
  selector:
    app: zabbix-mysql
